version: '3.6'

networks:
  fastfeet-network:
    driver: bridge

services:
  fastfeet-api:
    build: .
    volumes:
      - .:/home/node/api
    environment:
      - DB_URL=fastfeet-db
    depends_on:
      - fastfeet-db
    networks:
      - fastfeet-network
    links:
      - fastfeet-db
    container_name: fastfeet-api
    command: yarn dev
    ports:
      - 3333:3333

  fastfeet-db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    volumes:
      - db_data:/var/lib/postgres/data

volumes:
  db_data:
