version: '3.6'

networks:
  fastfeet-network:
    driver: bridge

services:
  fastfeet-api:
    build: .
    volumes:
      - .:/home/node/api
    environment:
      - DB_URL=fastfeet-db
      - REDIS_URL=fastfeet-redis
    depends_on:
      - fastfeet-db
      - fastfeet-redis
    networks:
      - fastfeet-network
    links:
      - fastfeet-db
      - fastfeet-redis
    container_name: fastfeet-api
    command: yarn dev
    ports:
      - 3333:3333

  fastfeet-queue:
    build: .
    volumes:
      - .:/home/node/api
    environment:
      - DB_URL=fastfeet-db
      - REDIS_URL=fastfeet-redis
    depends_on:
      - fastfeet-db
      - fastfeet-redis
    networks:
      - fastfeet-network
    links:
      - fastfeet-db
      - fastfeet-redis
    container_name: fastfeet-queue
    command: yarn queue

  fastfeet-db:
    image: postgres
    container_name: fastfeet-db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - db_data:/var/lib/postgres/data
    networks:
      - fastfeet-network

  fastfeet-redis:
    image: bitnami/redis:latest
    container_name: fastfeet-redis
    restart: always
    networks:
      - fastfeet-network
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - REDIS_PASSWORD=${REDIS_PASS}
    volumes:
      - redis_data:/bitnami/redis/data

volumes:
  db_data:
  redis_data:
